[package]
name = "tunneled"
version = "0.1.0"
edition = "2021"
authors = ["Juliandev02"]
license = "GPL-3"
repository = "https://github.com/Strawberry-Foundations/tunneled"

keywords = ["network", "cli", "tunnel", "tcp"]
categories = ["network-programming", "web-programming", "command-line-utilities"]
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0.56", features = ["backtrace"] }
lazy_static = "1.4.0"
stblib = "0.4.1"
clap = { version = "4.0.22", features = ["derive", "env"] }
reqwest = "0.11.23"
dashmap = "5.2.0"
fastrand = "2.0.1"
futures-util = { version = "0.3.21", features = ["sink"] }
hex = "0.4.3"
hmac = "0.12.1"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
sha2 = "0.10.2"
tokio = { version = "1.17.0", features = ["rt-multi-thread", "io-util", "macros", "net", "time"] }
tokio-util = { version = "0.7.1", features = ["codec"] }
tracing = "0.1.32"
tracing-subscriber = "0.3.10"
uuid = { version = "1.2.1", features = ["serde", "v4"] }

[dev-dependencies]
lazy_static = "1.4.0"
rstest = "0.18.2"
tokio = { version = "1.17.0", features = ["sync"] }