[package]
name = "tunneled"
version = "2.4.1"
edition = "2021"
authors = ["Juliandev02"]
license = "GPL-3"
repository = "https://github.com/Strawberry-Foundations/tunneled"

keywords = ["network", "cli", "tunnel", "tcp"]
categories = ["network-programming", "web-programming", "command-line-utilities"]
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0.89", features = ["backtrace"] }
lazy_static = "1.5.0"
stblib = "0.6.3-pre1"
clap = { version = "4.5.18", features = ["derive", "env"] }
reqwest = "0.12.7"
dashmap = "6.1.0"
fastrand = "2.1.1"
futures-util = { version = "0.3.30", features = ["sink"] }
hex = "0.4.3"
hmac = "0.13.0-pre.4"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
serde_yaml = "0.9.34"
sha2 = "0.11.0-pre.3"
tokio = { version = "1.40.0", features = ["rt-multi-thread", "io-util", "macros", "net", "time"] }
tokio-util = { version = "0.7.12", features = ["codec"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
uuid = { version = "1.10.0", features = ["serde", "v4"] }
dirs = "5.0.1"
xdg = "2.5.2"
serialport = "4.5.1"

[profile.release]
opt-level = 'z'
strip = true
lto = true
